// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('of4App').controller('MainCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS_after_again', 'Karma'];
  });

}).call(this);
