// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('of4App').controller('MainCtrl', function($scope, GoogleMap) {
    $scope.map = GoogleMap;
    return $scope.map.resizeMapEl();
  });

}).call(this);
