// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('of4App').controller('MainCtrl', function($scope, GoogleMap) {
    GoogleMap.win[0].google.maps.event.trigger(map, 'resize');
    return $scope.map = GoogleMap;
  });

}).call(this);
