// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('of4App').controller('MapCtrl', function($scope, GoogleMap) {
    return $scope.map = GoogleMap;
  });

}).call(this);
