// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('of4App').controller('MapCtrl', [
    "$scope", "GoogleMap", "$route", "$routeParams", "$location", function(scope, GoogleMap, route, routeParams, location) {
      scope.map = GoogleMap;
      scope.route = route;
      scope.routeParams = routeParams;
      scope.location = location;
      return scope.$watch("routeParams", (function(newVal, oldVal) {
        return angular.forEach(newVal, function(v, k) {
          console.log("routeParams");
          return location.search(k, v);
        });
      }), true);
    }
  ]);

}).call(this);
