// Generated by CoffeeScript 1.6.1
(function() {
  var MapsController;

  MapsController = function($scope) {
    return angular.extend($scope, {
      /*
      the initial center of the map
      */

      centerProperty: {
        lat: 45,
        lng: -73
      },
      /*
      the initial zoom level of the map
      */

      zoomProperty: 8,
      /*
      list of markers to put in the map
      */

      markersProperty: [
        {
          latitude: 45,
          longitude: -74
        }
      ],
      clickedLatitudeProperty: null,
      clickedLongitudeProperty: null
    });
  };

  (function() {
    var module;
    return module = angular.module("of4App", ["google-maps"]);
  })();

}).call(this);
