// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('of4App', []).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).when('/map', {
      templateUrl: 'views/map.html',
      controller: 'MapCtrl'
    });
  }).run(function($rootScope, $location) {
    var rootScope;
    rootScope = $rootScope;
    rootScope.navBarHeight = 40;
    return rootScope.mapShown = function() {
      return $location.path().indexOf('/map') > -1;
    };
  });

}).call(this);
