// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('of4App', []).config(function($routeProvider) {
    return $routeProvider.when('/menu', {
      templateUrl: 'views/menu.html',
      controller: 'MainCtrl'
    }).when('/list', {
      templateUrl: 'views/list.html',
      controller: 'MainCtrl'
    }).when('/map', {
      templateUrl: 'views/map.html',
      controller: 'MapCtrl'
    }).when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).otherwise({
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    });
  }).run(function($rootScope, $location) {
    var rootScope;
    rootScope = $rootScope;
    rootScope.navBarHeight = 40;
    rootScope.mapShownOnce = false;
    return rootScope.mapShown = function() {
      var mapShown;
      mapShown = $location.path().indexOf('/map') > -1;
      if (mapShown && !rootScope.mapShownOnce) {
        rootScope.mapShownOnce = true;
      }
      return mapShown;
    };
  });

}).call(this);
