// Generated by CoffeeScript 1.6.1
(function() {
  'use strict';
  angular.module('of4App', []).config(function($routeProvider, $locationProvider) {
    $locationProvider.html5Mode(true);
    return $routeProvider.when('/menu', {
      templateUrl: 'views/menu.html',
      controller: 'MainCtrl'
    }).when('/list', {
      templateUrl: 'views/list.html',
      controller: 'MainCtrl'
    }).when('/map', {
      templateUrl: 'views/map.html',
      controller: 'MainCtrl'
    }).when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).otherwise({
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    });
  }).run(function($rootScope, $location) {
    var rootScope;
    rootScope = $rootScope;
    rootScope.navBarHeight = 40;
    return rootScope.mapShown = function() {
      return $location.path().indexOf('/map') > -1;
    };
  });

}).call(this);
